Algoritmo "questao9"

Var
// Seção de Declarações das variáveis 
idade, mes, dia: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual a sua idade em anos? ")
leia(idade)
escreva("Quantos meses se passaram desde seu último aniversário? ")
leia(mes)
escreva("Da data do seu aniversário neste mês, quantos dias se passaram? ")
leia(dia)
escreva("Seu total de dias vividos foram ", idade * 365 + mes * 30 + dia)

Fimalgoritmo