Algoritmo "questao4"
// Desenvolver um programa que apresente os resultados de uma tabuada de um
// número qualquer.
Var
// Seção de Declarações das variáveis 
num, mult: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva( "Escreva um número e mostraremos sua tabuada: " )
leia(num)

para mult de 1 ate 10 passo 1 faca
escreval(num, " x", mult, " =", num * mult)
fimpara

Fimalgoritmo