Algoritmo "questao2"
// Desenvolver um programa que apresente o total da soma de N números inteiros
// do número 1 até N.
Var
// Seção de Declarações das variáveis 
acumulador, num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
acumulador <- 0

escreva("Escreva um número: ")
leia(num)

para num de 1 ate num faca
     acumulador <- acumulador + num
fimpara
escreva(acumulador)
Fimalgoritmo