Algoritmo "QUESTAO6"
// Fazer um algoritmo que peça um número, e ao final, informe se o número
// digitado está acima de 1000 ou abaixo de 1000.
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Informe um número: ")
leia(num)

se num < 1000 entao
   escreva("Seu número é menor que 1000.")
senao
   escreva("Seu número é maior que 1000.")
fimse

Fimalgoritmo
