Algoritmo "questao4"

Var
// Seção de Declarações das variáveis 
contador: inteiro
acumulador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
acumulador <- 0

enquanto (contador <= 100) faca
         acumulador <- acumulador + contador
         contador <- contador + 1
fimenquanto

escreva("A soma de todos os números de 1 a 100 é",  acumulador)

Fimalgoritmo