Algoritmo "questao14"

Var
// Seção de Declarações das variáveis 
fator: inteiro
mult: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
fator <- 5
mult <- 1

enquanto fator > 1 faca
         fator <- fator - 1
         mult <- 5 * fator
         fator <- fator - 1
         mult <- mult * fator
         fator <- fator - 1
         mult <- mult * fator
         fator <- fator - 1
         mult <- mult * fator
fimenquanto
escreva(mult)


Fimalgoritmo